# Generated by Django 2.1.7 on 2019-03-22 07:26

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='gooduser',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='gooduser',
            name='identifier',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
