# Generated by Django 2.1.7 on 2019-03-22 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20190322_0726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gooduser',
            name='email',
        ),
    ]
