# Generated by Django 2.1.7 on 2019-03-22 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_remove_gooduser_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gooduser',
            old_name='identifier',
            new_name='username',
        ),
    ]
