# Generated by Django 2.1.7 on 2019-03-22 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_auto_20190322_0750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gooduser',
            name='username',
        ),
        migrations.AddField(
            model_name='gooduser',
            name='user_id',
            field=models.PositiveIntegerField(default=0, unique=True),
        ),
    ]
