# Generated by Django 2.1.7 on 2019-03-22 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_gooduser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gooduser',
            name='user_id',
        ),
    ]
