# Generated by Django 2.1.7 on 2019-03-27 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_remove_gooduser_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='gooduser',
            name='userID',
            field=models.SmallIntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='gooduser',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
