CREATE TABLE Account (
  userID INT UNSIGNED NOT NULL AUTO_INCREMENT,
  username VARCHAR(30) NOT NULL UNIQUE,
  password VARCHAR(120) NOT NULL,
  characterName VARCHAR(30) NOT NULL,
  experience INT UNSIGNED default 0,
  gold INT UNSIGNED default 0,
  guildID VARCHAR(60) NULL,
  PRIMARY KEY (userID)
);

CREATE TABLE Inventory (
  userID INT UNSIGNED NOT NULL,
  itemID BIGINT UNSIGNED NOT NULL, 
  PRIMARY KEY (userID, itemID),
  FOREIGN KEY (itemID) REFERENCES Item (itemID),
  FOREIGN KEY (userID) REFERENCES Account (userID)
    ON DELETE CASCADE
);

CREATE TABLE Item (
  itemID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  itemName VARCHAR(120) NOT NULL,
  itemDescription TEXT NOT NULL,
  itemType INT UNSIGNED NOT NULL,
  itemRating INT UNSIGNED NOT NULL,
  itemValue INT UNSIGNED NOT NULL,
  itemModifiers TEXT NOT NULL,
  userID INT UNSIGNED NOT NULL,
  PRIMARY KEY (itemID),
  FOREIGN KEY (userID) REFERENCES Account (userID)
    ON DELETE CASCADE
);

CREATE TABLE Guild (
  guildID INT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(120) NOT NULL,
  owner INT UNSIGNED NOT NULL,
  PRIMARY KEY (guildID),
  FOREIGN KEY (owner) REFERENCES Account (userID)
    ON DELETE CASCADE
);

CREATE TABLE Member (
  userID INT UNSIGNED NOT NULL,
  guildID INT UNSIGNED NOT NULL,
  admin SMALLINT UNSIGNED default 0,
  PRIMARY KEY (userID),
  FOREIGN KEY (userID) REFERENCES Account (userID)
    ON DELETE CASCADE,
  FOREIGN KEY (guildID) REFERENCES Guild (guildID)
    ON DELETE CASCADE
);

